### ISSUE TITLE
Submit to TestFlight

### ISSUE THREAD

**Issue by saagarjha** [saagarjha/MacCast#10]

**Comment by saagarjha** [comment]
App is working its way through review

**Comment by saagarjha** [comment]
0.1 (3) has been rejected. Just sent out 0.1 (4) with some changes to help address their feedback.

**Comment by saagarjha** [comment]
TestFlight build 0.1 (4) has been accepted for macOS. visionOS build is still in review.

**Comment by iammatthias** [comment]
Link for TestFlight?

**Comment by austinarchibald** [comment]
What’s the latest?

**Comment by saagarjha** [comment]
The initial visionOS build has been approved and it seems like subsequent builds for 0.1 are unlikely to see similar delays. I am working on preparing a TestFlight alpha for both platforms.

**Comment by saagarjha** [comment]
TestFlight alpha will be going up shortly

**Comment by saagarjha** [comment]
https://testflight.apple.com/join/Pq1HzHqe in case you missed it

**Comment by danburkhol** [comment]
Do you have a pre-built macOS companion app or do I need to build from source?

Looking forward to trying this out!

**Comment by saagarjha** [comment]
It's also on TestFlight
