### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by AntDX316** [saagarjha/MacCast#19]
How do you run this?

**Comment by saagarjha** [comment]
The easiest way to try this code right now would be to download it and build it using Xcode. It will sign and deploy it to your device.

**Comment by AntDX316** [comment]
I did, just change the team makes it work?

**Comment by AntDX316** [comment]
It doesn't seem to work the windows within the AVP Simulator. Will it work on the real one?

**Comment by saagarjha** [comment]
Yep, just change this to match your team: https://github.com/saagarjha/Ensemble/blob/7ff057afd8a49b5723e12471dbedeff50fdf46bb/Configs/Deployment.xcconfig#L10. If you have a free developer account you might need to also modify the bundle ID and/or signing identity (also in the configs) but I haven’t done that in a while so I can’t say for sure.

**Comment by AntDX316** [comment]
yea, I got it to work with just by changing the team to mine.

so, this works with the eye tracking?

**Comment by AntDX316** [comment]
can you keep updating it to ensure it always works? : )

**Comment by saagarjha** [comment]
> It doesn't seem to work the windows within the AVP Simulator. Will it work on the real one?

Ensemble should be able to cast your Mac windows both from the simulator and on a real device. Trying to control things from the Mac you're on is unlikely to work very well. Are you running into issues?

> so, this works with the eye tracking?

I don't have any special code for this, but it supports the system behaviors.

> can you keep updating it to ensure it always works? : )

This is my side project, so I can't ensure this. But I plan to use this myself so I will probably keep updating it to the point where I am either happy with it or I think there is something else that I'd rather work on.

**Comment by AntDX316** [comment]
Ensuring eye tracking would be good as a 2nd input.

I’m using the iPhone Remote, Mouse & Keyboard app to make it easier to do things through the Apple Watch and the iPhone but it could be hard to see through the goggles.

**Comment by saagarjha** [comment]
I think this is the same as #17

**Comment by saagarjha** [comment]
Closing as I think the question of how to run this is resolved and the other feedback is already tracked. (Feel free to let me know if either is not the case.)
