### ISSUE TITLE
You're sitting on a gold mine.

### ISSUE THREAD

**Issue by kensuddaby** [saagarjha/MacCast#20]
From what I've read on all the forums, if you could get this working, there will be a LOT of people that would want this app. It would be a killer app for people actually wanting to do work on the AVP.

**Comment by austinarchibald** [comment]
Going to sideload this as soon as the UPS man delivers!

**Comment by kensuddaby** [comment]
Nice,

Let me know how it goes!!!

**Comment by saagarjha** [comment]
Closing since this isn't really a bug
