### ISSUE TITLE
Loading Windows forever

### ISSUE THREAD

**Issue by albertotono** [saagarjha/MacCast#23]
My windows are loading forever. 

I am building it from my laptop via wifi.. 
from xCode I build both Mac and Apple Vision Pro application.. 
It asks to place a "6-digit code" but automatically connect without allow me to add that code... it is strange.. why? 

The when I click on my Mac in the Ensemble App on the Apple VIsion Pro.. the windows are loading forever? 

Any suggestions

**Comment by austinarchibald** [comment]
I also did not have to enter the code (maybe because it's already paired and trusted via xcode). But my windows loaded immediately. Working great! Only additional thing I did was, maybe try enabling Screen recording and Accessibility permissions in macOS Settings > Privacy & Security. This is a great start @saagarjha ! ~Immediate needed feature I can think of is ability to increase the size of the windows. Can't change it at all.~ Nevermind, I was choosing a sideloaded iPad app (Apollo) on my Mac, which wouldn't allow me to change window size. Standard macOS windows do!

**Comment by saagarjha** [comment]
> It asks to place a "6-digit code" but automatically connect without allow me to add that code... it is strange.. why?

Authentication is currently disabled because it is incredibly annoying to deal with during development

> The when I click on my Mac in the Ensemble App on the Apple VIsion Pro.. the windows are loading forever?

Do you see a list of windows?

**Comment by albertotono** [comment]
<img width="487" alt="Screenshot 2024-02-03 at 6 29 33 AM" src="https://github.com/saagarjha/Ensemble/assets/11828200/53c6f1f2-b6ee-45e7-9e29-04f5f6d315ba">
This is what I see in Accessibility @austinarchibald I am on my M3 Macbook Pro

No there is no list of windows... it was just loading forever. 

Is important to change the bundle identifier? it keep using "com.saagarjha.MacCast" how can I change it?

**Comment by albertotono** [comment]
These are the log: "fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x280e42ad0 UILayoutGuide:0x2814487e0'TitleViewGuide(0x10130cf80)'.trailing <= UILayoutGuide:0x281448b60'UIViewLayoutMarginsGuide'.trailing   (active)>",
    "<NSLayoutConstraint:0x280e42a80 UILayoutGuide:0x2814487e0'TitleViewGuide(0x10130cf80)'.leading >= UILayoutGuide:0x281448b60'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x280eff750 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x10130cc00'Available Macs'.width == 0   (active)>",
    "<NSLayoutConstraint:0x280e428f0 'UIView-leftMargin-guide-constraint' H:|-(24)-[UILayoutGuide:0x281448b60'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UINavigationBarContentView:0x10130cc00'Available Macs' )>",
    "<NSLayoutConstraint:0x280e42990 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x281448b60'UIViewLayoutMarginsGuide']-(24)-|(LTR)   (active, names: '|':_UINavigationBarContentView:0x10130cc00'Available Macs' )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x280e42ad0 UILayoutGuide:0x2814487e0'TitleViewGuide(0x10130cf80)'.trailing <= UILayoutGuide:0x281448b60'UIViewLayoutMarginsGuide'.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x280ee3de0 UILayoutGuide:0x281441340'TitleViewGuide(0x101438a70)'.trailing <= UILayoutGuide:0x2814416c0'UIViewLayoutMarginsGuide'.trailing   (active)>",
    "<NSLayoutConstraint:0x280ee3d90 UILayoutGuide:0x281441340'TitleViewGuide(0x101438a70)'.leading >= UILayoutGuide:0x2814416c0'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x280e87110 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x101446de0.width == 0   (active)>",
    "<NSLayoutConstraint:0x280ee3c00 'UIView-leftMargin-guide-constraint' H:|-(24)-[UILayoutGuide:0x2814416c0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UINavigationBarContentView:0x101446de0 )>",
    "<NSLayoutConstraint:0x280ee3ca0 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x2814416c0'UIViewLayoutMarginsGuide']-(24)-|(LTR)   (active, names: '|':_UINavigationBarContentView:0x101446de0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x280ee3de0 UILayoutGuide:0x281441340'TitleViewGuide(0x101438a70)'.trailing <= UILayoutGuide:0x2814416c0'UIViewLayoutMarginsGuide'.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
nw_socket_initialize_socket [C1:2] setsockopt SO_NECP_CLIENTUUID failed [22: Invalid argument]
nw_socket_initialize_socket setsockopt SO_NECP_CLIENTUUID failed [22: Invalid argument]
AggregateDictionary is deprecated and has been removed. Please migrate to Core Analytics.
nw_socket_copy_info [C1:2] getsockopt TCP_INFO failed [102: Operation not supported on socket]
nw_socket_copy_info getsockopt TCP_INFO failed [102: Operation not supported on socket]
Class for component AccessibilityComponent already registered
Class for component ImageBasedLightComponent already registered
Component Shadow already registered
Component Shadow already registered
[USDImportService] RealityIO USDImportService instantiated.  RealityIO will be used to service load requests from USDImportService.
     CAReportingClient.mm:532   Attempted to remove a reporter not created by this client { careporter_id=1975684956161 }

**Comment by saagarjha** [comment]
Are you able to see the "Select a window" screen on visionOS? Have you given Ensemble screen recording permission?

**Comment by BenArtes** [comment]
How do you give Ensemble Screen Recording permission?

**Comment by saagarjha** [comment]
Follow this guide and find Ensemble in the list: https://support.apple.com/guide/mac-help/control-access-screen-system-audio-recording-mchld6aa7d23/mac

**Comment by saagarjha** [comment]
The latest commit also has a button to open that view for you.

**Comment by BenArtes** [comment]
Yep, latest commit correctly pulls up settings. Once permissions were given, this error went away. Thanks. (Note, not OP)

**Comment by saagarjha** [comment]
Closing, I think I've fixed this on my side. If you want to test this try the TestFlight builds and if you still have issues with that feel free to let me know.
