### ISSUE TITLE
What are the exact steps to run this on the AVP?

### ISSUE THREAD

**Issue by AntDX316** [saagarjha/MacCast#26]
What are the exact steps to run this on the AVP?

My AVP is paired to the Mac.
The AVP is hooked up to the Devices area of Xcode.

Running Ensemble on the AVP, I cannot select the MacBook in the Remote Device list of Ensemble.
It works on the AVP **Simulator** but not on the **Actual** AVP.

**Comment by saagarjha** [comment]
Are you running the latest commit?

**Comment by AntDX316** [comment]
Does the latest commit make it work? Does it work on yours?

**Comment by saagarjha** [comment]
Of course it works for me, I wrote it :) The latest commit is an attempt to make it work better on other people's machines. Give it a try and see if it helps you!

**Comment by AntDX316** [comment]
nice, I will try it later

**Comment by Geczy** [comment]
This is the issue I'm currently having too, nothing shows in the available mac list

I'm using the real AVP not a simulator, and on the latest commit. I allowed all the network privacy requests

![IMG_0023](https://github.com/saagarjha/Ensemble/assets/1036968/0cf7225b-3899-4283-b154-ae1b4b1414f4)

**Comment by Geczy** [comment]
Scratch that, I did a build clean and build install, and also force closed Ensemble on the AVP, and now it's working!

![CleanShot 2024-02-05 at 10 04 21@2x](https://github.com/saagarjha/Ensemble/assets/1036968/549782c1-b49c-4c07-aa45-a7cc781f6b1e)

**Comment by AntDX316** [comment]
tcp_timers [C2:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_output [C1:3] flags=[R.] seq=899875799, ack=2591773116, win=65535 state=CLOSED rcv_nxt=2591773116, snd_una=899875798
tcp_timers [C6:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C5:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C4:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C3:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C21:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C20:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C19:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C18:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C17:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C16:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C15:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C14:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C13:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C12:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C11:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C10:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C9:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C8:3] TCP listener failed to receive inbound connection within timeout, dropping connection
tcp_timers [C7:3] TCP listener failed to receive inbound connection within timeout, dropping connection

I get this error now. When selecting M3, it disappears soon after instead of nothing happening.
Xcode says that.

**Comment by AntDX316** [comment]
Clean and Build fixed it : )

**Comment by AntDX316** [comment]
problem is, unless the app is designed for AVP eye tracking, you cannot interact with anything? : (

**Comment by AntDX316** [comment]
its pretty much useless still but the flying windows are cool..

**Comment by AntDX316** [comment]
trying to add windows after a while with the + icon does nothing

**Comment by AntDX316** [comment]
ensemble needs a lot of work : (

**Comment by AntDX316** [comment]
/Users/antdx/Ensemble/macOS/Local.swift
/Users/antdx/Ensemble/macOS/Local.swift:124:46 Non-sendable type 'CMSampleBuffer?' returned by implicitly asynchronous call to actor-isolated function cannot cross actor boundary

/Users/antdx/Ensemble/macOS/Local.swift:134:41 Non-sendable type 'AsyncStream<CMSampleBuffer>' returned by implicitly asynchronous call to actor-isolated function cannot cross actor boundary

/Users/antdx/Ensemble/macOS/Local.swift:137:23 Capture of 'stream' with non-sendable type 'AsyncStream<CMSampleBuffer>' in a `@Sendable` closure

/Users/antdx/Ensemble/macOS/Local.swift:139:41 Capture of 'frame' with non-sendable type 'CMSampleBuffer' in a `@Sendable` closure


/Users/antdx/Ensemble/macOS/ScreenRecorder.swift
/Users/antdx/Ensemble/macOS/ScreenRecorder.swift:59:40 Non-sendable type 'CMSampleBuffer' returned by implicitly asynchronous call to nonisolated function cannot cross actor boundary

**Comment by AntDX316** [comment]
The Opened Windows don't sync up with what I'm doing on the MacBook. They are just static windows.

**Comment by AntDX316** [comment]
The eye tracking was working temporarily when I put the headset on but without a pointer, it's impossible to see where it is at. It stopped worked soon after of course.

**Comment by AntDX316** [comment]
If we had:
-the ability to use a controller like the Meta Quest Pro with the pointer
-ability to zoom and make windows bigger
-it sync up directly with what is going on the MacBook,

It would be good.

**Comment by BenArtes** [comment]
> ensemble needs a lot of work : (

I know the AVP is new and finding a new project like this is exciting and you're maybe hoping for more than ensemble currently does, but creating a ton of issue comments and negative comments like this isn't really polite and doesn't really belong here.

saagarjha has made something cool with a lot of potential, but its not even alpha or beta software at this point, just a prototype that they've been kind enough to share.

Also, issues are more for documenting specific bugs (and good issues require a decent amount of work to file because you need to provide a lot of information to help debug) more than just documenting your experience.

**Comment by saagarjha** [comment]
Feel free to file more specific issues for things you are looking for
