### ISSUE TITLE
Unable to extract cached certificates from the SSL_SESSION object

### ISSUE THREAD

**Issue by billyjacoby** [saagarjha/MacCast#28]
Running into this issue when running locally. The mac I'm using here is on the latest macOS beta, not sure if that could affect anything.
Full error message:

macOS:
`boringssl_session_set_peer_verification_state_from_session(448) [C1:2][0x10fc06c60] Unable to extract cached certificates from the SSL_SESSION object`

visionOS is stuck on the "Loading windows..." screen.

Happy to provide anything else to help here.

**Comment by billyjacoby** [comment]
Actually wondering if this should be moved to [this repo ](https://github.com/saagarjha/AppleConnect/issues)instead

**Comment by saagarjha** [comment]
I think that message is unrelated, but see if the latest commit presents anything about missing permissions.

**Comment by billyjacoby** [comment]
Nothing about missing permissions, but everything seems to be running in the simulator properly now. Will test on Vision in a bit and close the issue if everything is fixed. Thanks!

**Comment by billyjacoby** [comment]
Hmm getting TCP timeouts on device now:

`tcp_timers [C12:3] TCP listener failed to receive inbound connection within timeout, dropping connection`

**Comment by saagarjha** [comment]
Are you seeing issues with connectivity? I think that's just spam, the network connection should generally recover without having to do anything yourself.

**Comment by billyjacoby** [comment]
I'm actually thinking this might have something to do with Screen Recording access, when I click the "Request Access" now Ensemble doesn't show up as an option in settings now.

Not sure what would have changed this, and the Accessiblity request works and succeeds fine

**Comment by saagarjha** [comment]
Does `tccutil reset ScreenCapture com.saagarjha.MacCast` help

**Comment by billyjacoby** [comment]
I actually ended up clearing Derived Data and restarting my laptop and that seemed to do it
