### ISSUE TITLE
This is how you run

### ISSUE THREAD

**Issue by ronangrant** [saagarjha/MacCast#30]
First, the issue I am having is that it is laggy, it takes a bit for what I do on my computer to relay to the APV, making it almost unusable.

If you are wondering how to connect Xcode to APV:

Connect to same wifi network
On Vision Pro -> Settings > General > Remote Devices
On Mac -> Xcode -> Devices & Simulators -> Select the Vision Pro & enter the code
On Vision Pro -> Privacy & Security > Developer Mode
On Mac -> Run a build targeted at your vision pro device which should now be a run 

To run on xcode, you need to clone the repo, go to file -> Open -> And open the project. Next, to get started you need to sign:

**1. Change Team ID**
Open Xcode Preferences (Cmd + ,).
Go to the 'Accounts' tab.
Add your Apple Developer account here by clicking the + and following the prompts.
Once you've added your account, you can close the Preferences.
**2. Change Signing Configuration**
Open the Xcode project.
Select the project in the Project Navigator to view the project settings.
For each target (macOS and visionOS), go to the 'Signing & Capabilities' tab.
Change the 'Team' to your own Apple Developer account.
Xcode should then automatically manage the provisioning profiles for you. If not, you may need to create them manually in the Apple Developer portal.

When you want to install the macos app, you have to select MacOS as the location. Same with VisionPro:

<img width="371" alt="Screenshot 2024-02-06 at 5 03 17 PM" src="https://github.com/saagarjha/Ensemble/assets/67560747/0aae8fdb-e7b0-407e-b41d-a7d6d7bd0257">

When building for the APV I had to change the Bundle Identifier to something else. From:
com.saagarjha.MacCast 
to
com.[YourDomain].[AppName]

The bundle identifier is a unique string that identifies your app within the Apple ecosystem and on devices. It is used by iOS and macOS to recognize your app and differentiate it from others in the App Store and on the device. All you need to do is change it to be something else like: com.yourname.Ensemble

If you have any specific questions, let me know. Or, ask an AI.

**Comment by saagarjha** [comment]
> First, the issue I am having is that it is laggy, it takes a bit for what I do on my computer to relay to the APV, making it almost unusable.

How's Mac Virtual Display work for you, if you've tried that? I am tracking stuff like that in #15 but there are a lot of things that can be done here.

Also, FWIW, the team ID is in Configs/Deployment.xcconfig. I should probably move the bundle ID there as well, now that they're shared across targets…

**Comment by saagarjha** [comment]
Closing because there are general instructions in the README now and people who still need help can search for this if they need it. And, well, this isn't an issue and there's also a TestFlight build now
