### ISSUE TITLE
How to set up?

### ISSUE THREAD

**Issue by EasonC13** [saagarjha/MacCast#34]
I download the Mac version .app file and open it successfully.

Then, I airdrop the vision pro one to the vision pro. But I don't know where I can open Ensemble.app in vision pro.

What should I do next?

**Comment by saagarjha** [comment]
In general you're going to have to sign the app to load it onto Apple Vision Pro; the assets I upload are mostly there so you can symbolicate reports. I think the easiest way to install the app right now would be to build it from source.

**Comment by EasonC13** [comment]
Tried it at stimulator. That is amazing!

Yet, it seems I need a valid developer signature to put it into Vision Pro (?)
How to get it? Should I use the account that subscribed and registered as Apple developer?

<img width="731" alt="image" src="https://github.com/saagarjha/Ensemble/assets/43432631/944a360f-2279-4b81-8710-0305b013fca4">

**Comment by EasonC13** [comment]
Update, I follow https://github.com/saagarjha/Ensemble/issues/30, and it works!

I just sent you an email for a video of my usage, bugs, and feedback on Ensemble in Vision Pro.
