### ISSUE TITLE
Mac cast to Eyesight screen

### ISSUE THREAD

**Issue by yosun** [saagarjha/MacCast#36]
Hey this would be a super cool feature. ktnxbai! <3

**Comment by saagarjha** [comment]
I’m sorry, I don’t know what that is 😅 Do have a link or something so I can learn more about it?

**Comment by yosun** [comment]
the front outer screen of the AVP- is it called the eyesight screen?

**Comment by saagarjha** [comment]
Ah. There's no programmatic access to that to my knowledge, so I don't think this is something we can support. I'd be happy to reopen this if it gets added or someone makes a jailbreak or something that provides access.

**Comment by yosun** [comment]
i heard you are a legendary hacker, so please look into it.
